Received: from EXC11.spk.no ([fe80::113e:3247:8439:f17f]) by EXC21.spk.no
 ([fe80::a1d8:12b5:2b5f:7659%11]) with mapi id 14.02.0342.003; Wed, 24 Apr
 2013 08:11:11 +0200
From: Torunn Marstrander <torunn.marstrander@spk.no>
To: Nils Ove Erstad <nils.ove.erstad@spk.no>
CC: Viktor Varland <viktor.varland@spk.no>
Subject: SV: Input Victor Varland
Thread-Topic: Input Victor Varland
Thread-Index: Ac4/U1FA/esOaig9TKWgRzWGti2t8QBXR2Dg
Date: Wed, 24 Apr 2013 06:11:10 +0000
Message-ID: <E4EF62A7D0A5F948A6690C77FC1203062053C55D@EXC11.spk.no>
References: <9A486FEF1BE27046804905BAFADF8696205E0A26@EXC11.spk.no>
In-Reply-To: <9A486FEF1BE27046804905BAFADF8696205E0A26@EXC11.spk.no>
Accept-Language: nb-NO, en-US
Content-Language: nb-NO
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: EXC21.spk.no
X-MS-Has-Attach:
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator:
x-originating-ip: [10.20.3.61]
Content-Type: multipart/alternative;
  boundary="_000_E4EF62A7D0A5F948A6690C77FC1203062053C55DEXC11spkno_"
MIME-Version: 1.0

--_000_E4EF62A7D0A5F948A6690C77FC1203062053C55DEXC11spkno_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Hei,

Viktor har nå vært en del av FPX siden 1. september og ha han har vært=
en stor bidragsyter for utviklingen av nytt servicedesksystem for ITO sam=
t oppbygging av struktur på FPX forvaltning. Han er hele tiden «forover=
lent» og løsningsorientert.  Han er selvgående og leverer alltid oppg=
aver av høy kvalitet.

Han har god dialog med brukere på alle nivåer av organisasjonen og jeg =
mottar gode tilbakemeldinger.  Han har meget dyktig faglig og sosialt og de=
tte er veldig viktig i et lite team som FPX.

Jeg er heldig som har Viktor på teamet og gir han mine beste anbefalinger=
.

Mvh,
Torunn
